
version: '3.9'

services:
   database:
    image: postgres:latest
    container_name: database_uaifood
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=uaifood
    volumes:
      - pgdata:/data/postgres
   app:
    build: .
    container_name: uaifood-api
    depends_on:
      - database
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
